### PR TITLE
Change CTRL to Ctrl

### PR DESCRIPTION
**Pull request by vanillajonathan**
As per modern notation.

### CODE REVIEW

**Comment by nE0sIghT** [comment]
Please change your commit email to valid one

**Comment by nE0sIghT** [comment]
@vanillajonathan ping

**Comment by vanillajonathan** [comment]
I don't know how to that on something that is already sent in as a pull request.
I edit from the GitHub website and the email is set to private since it uses workplace email address and this is a non-work related private commit.

Perhaps you could merge the change without commiting this pull request?

**Comment by nE0sIghT** [comment]
You should use real email if you want to be author of commit.
You can clone your repository, set real email, amend commit and force push it.

**Comment by vanillajonathan** [comment]
I don't really care about being the author.

**Pull request closed without merging**
